### ISSUE TITLE
Install issue under Debian GNU/Linux

### ISSUE THREAD

**Issue by jmfriedt** [MLP-Hub/MLP_IA_Suite#1]
After adding ``apt install python3-sklearn  python3-torch python3-skimage``, the plugin installation fails because of ``MLP_IA_Suite/pylc_master/pylc.py``. Commenting out the code from this file allows for the installation to complete, and the plugin to execute in QGIS 3.34, otherwise a lengthy series of error messages during install ends with
```
  File "...python/plugins/MLP_IA_Suite/pylc_master/pylc.py", line 16, in 
    from mlp_ia_suite.pylc_master.test import tester
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mlp_ia_suite'
```
All other import paths are relative but this ``from mlp_ia_suite.pylc_master.test import tester`` is not, I am unable to correct the issue myself other than commenting the content of this file.

**Comment by ClaireWrightMi** [comment]
We just pushed a fix for this based on testing with MacOS Unix system. We don't have immediate access to a Debian system for testing, but please proceed to try re-installing the plugin with this fix.

**Comment by benjaminwrightmi** [comment]
This fix has now been tested on a fresh Debian install - as you have alluded to also note that the plugin will require some extra python packages not listed in the README as QGIS defaults to system python in Debian rather than an included python with pre-installed packages on Windows and MacOS. These are: seaborn, sklearn.

**Comment by jmfriedt** [comment]
I confirm that after installing ``python3-seaborn`` the plugin now installs perfectly on Debian GNU/Linux. Thank you for your help.
